/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package splash;

import jarvis.ProjectJarvis;
import outputstream.SystemSounds;
import jarvis.VideoCap;
import jarvis.utilities.Utilities;
import outputstream.BlackBoard;
import java.awt.Color;
import java.awt.Container;
import java.awt.Cursor;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.io.File;
import java.io.IOException;
import java.io.StringReader;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

import javax.swing.JEditorPane;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.ScrollPaneConstants;
import javax.swing.Timer;
import javax.swing.text.BadLocationException;
import javax.swing.text.Document;
import javax.swing.text.html.HTMLDocument;
import javax.swing.text.html.HTMLEditorKit;
import javax.swing.text.html.StyleSheet;
import static outputstream.BlackBoard.screenSize;

/**
 *
 * @author owoye001
 */
public class ProgressPanelOverlay extends javax.swing.JFrame {

   
    private JEditorPane jEditorPaneLoadCapture;
    private JScrollPane jScrollPaneLoadCapture;
    private Timer loadHtmlNicely;
    private HTMLDocument htmlDoc;
    public Container mainScreenComponentHolders;
    private int entry=0;
    public static BlackBoard blackBoard;

    /**
     * Creates new form capturescreen
     * @param moduleLoadListArrayList     
     * @param loadListArrayList
     */
    public ProgressPanelOverlay(ArrayList moduleLoadListArrayList, ArrayList loadListArrayList) {
       
        initComponents();
        
        //initializing html timer here 
        loadHtmlNicely = new Timer(0,null);
        
        //getting content pane of splash screen overlay here (capture screen)
        mainScreenComponentHolders = getContentPane();
        
        //getting screen size
        screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        
        //loading splash screen overlay here 
        setUpFrameCaptureJFrame(mainScreenComponentHolders, moduleLoadListArrayList);

        //loads the progress screen for loading individual files
        Timer loadIndividualFiles = new Timer(3000, (ActionEvent e) -> {
        
            //panelprogressoverlay
         java.awt.EventQueue.invokeLater(() -> {
            blackBoard = new BlackBoard(loadListArrayList);
        });  
        
        
        });
        loadIndividualFiles.setRepeats(false);
        loadIndividualFiles.start();
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(0, 102, 0));
        setUndecorated(true);
        setOpacity(0.55F);
        setResizable(false);
        getContentPane().setLayout(null);
        getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    private void reInitializeComponents(ArrayList moduleLoadListArrayList) {

        jEditorPaneLoadCapture = new JEditorPane();
        jScrollPaneLoadCapture = new JScrollPane(jEditorPaneLoadCapture);

        jScrollPaneLoadCapture.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPaneLoadCapture.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jEditorPaneLoadCapture.setBorder(null);
        jEditorPaneLoadCapture.setContentType("text/html");
        //jEditorPaneLoadCapture.setCaretColor(new Color(102, 255, 102));
        jEditorPaneLoadCapture.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        jEditorPaneLoadCapture.setForeground(new java.awt.Color(102, 255, 102));
        jEditorPaneLoadCapture.setEditable(false);
        jEditorPaneLoadCapture.setAutoscrolls(true);

        //adding a way to load html into editor
        // add a HTMLEditorKit to the editor pane
        HTMLEditorKit captureScreenKit = new HTMLEditorKit();
        jEditorPaneLoadCapture.setEditorKit(captureScreenKit);

        jEditorPaneLoadCapture.setName("");
        jScrollPaneLoadCapture.getViewport().setOpaque(false);

        jScrollPaneLoadCapture.setBounds(0, 0, screenSize.width, screenSize.height);
        jEditorPaneLoadCapture.setBounds(0, 0, screenSize.width, screenSize.height);

        // add some styles to the html
        StyleSheet styleSheet = captureScreenKit.getStyleSheet();
        styleSheet.addRule("body {background-color: #000; text-align: right; font-size: 120px; color:#ff0000; font-family: Arial; margin: 20px; padding: 20px; }");
        styleSheet.addRule("h1 {font-size: 1em; color: #FFD700; }"); //yellow
        styleSheet.addRule("h2 {color: #C5B358; font-size: .5em; text-align: left;}"); //gold
        styleSheet.addRule("h3 {color: #ff0000; font-size: .35em; text-align: left;}"); //red
        
        // create a document, set it on the jeditorpane, then add the html
        Document doc = captureScreenKit.createDefaultDocument();
        jEditorPaneLoadCapture.setDocument(doc);
        
        //loading from inside the jar file
        File splashBackground = new File(Utilities.getJarParentDir() + ProjectJarvis.settings.splashBackground);
        
        //main screen background 
        File mainScreenBackground = new File(Utilities.getJarParentDir() + ProjectJarvis.settings.mainScreenBackground);
        
        VideoCap vcap = new VideoCap(splashBackground.getAbsolutePath()); //take pic
        
        //resize main screen picture.
        ProjectJarvis.utilities.resizeImageAndReSave(mainScreenBackground);
        
        ProjectJarvis.utilities.resizeImageAndReSave(splashBackground);
       
        try {
            jEditorPaneLoadCapture.setText("<html><body style='color: #ffffff; background-color: #000; background-image: url(" + splashBackground.toURI().toURL() + "); '></body></html>");
        } catch (MalformedURLException ex) {}

        //inserting element here
        htmlDoc = (HTMLDocument) jEditorPaneLoadCapture.getDocument();

        loadHtmlNicely = new Timer(500, (ActionEvent e) -> {
            try {
               
                captureScreenKit.read(new StringReader(moduleLoadListArrayList.get(entry).toString()), htmlDoc, 1);
                entry++;
                if (entry>moduleLoadListArrayList.size()-1){
                   
                    loadHtmlNicely.stop();}
            } catch (IOException | IndexOutOfBoundsException | BadLocationException ex) {
                Logger.getLogger(ProgressPanelOverlay.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
        
        SystemSounds programload = new SystemSounds("programload");
                        programload.playsound();
        
       
        add(jScrollPaneLoadCapture); //add to Jpanel

    }

    

    private void setUpFrameCaptureJFrame(Container ScreenComponentHolders, ArrayList moduleLoadListArrayList) {
       
       ScreenComponentHolders.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR)); //changes the cursor to a wait cursor
       ScreenComponentHolders.setBackground(Color.black); //setting the background color of the content pane here
       ScreenComponentHolders.setLayout(null);
       
       reInitializeComponents(moduleLoadListArrayList);
     
       loadHtmlNicely.start(); //start timer for modules
        
        URL resource = ProgressPanelOverlay.class.getResource("/jarvis/images/bigme.gif");
        setIconImage(new ImageIcon(resource).getImage());
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setResizable(false);
        setTitle ("Jarvis Project"); //show current user in title
        setVisible(true);
    }

}
