/*
 * Copyright (C) 2016 owoye001
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package jarvis.inpustream;

import java.awt.event.KeyEvent;
import java.net.URL;
import javax.swing.ImageIcon;
import outputstream.MainPanel;
import outputstream.BlackBoard;

/**
 *
 * @author owoye001
 */
public class TextEntry extends javax.swing.JFrame {

    public String textEntered = ""; //no text has been entered
    /**
     * Creates new form TextEntry
     */
    public TextEntry() {
        initComponents();
        reInitialize();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldInput = new javax.swing.JTextField();
        jLabelTouchHere = new javax.swing.JLabel();
        jLabelBg = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);
        setOpacity(0.85F);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldInput.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jTextFieldInput.setForeground(new java.awt.Color(153, 0, 51));
        jTextFieldInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldInput.setBorder(null);
        jTextFieldInput.setCaretColor(new java.awt.Color(153, 0, 51));
        jTextFieldInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldInputKeyReleased(evt);
            }
        });
        getContentPane().add(jTextFieldInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 620, 50));

        jLabelTouchHere.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jarvis/images/thinking.gif"))); // NOI18N
        jLabelTouchHere.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelTouchHereMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelTouchHereMouseEntered(evt);
            }
        });
        jLabelTouchHere.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jLabelTouchHereKeyReleased(evt);
            }
        });
        getContentPane().add(jLabelTouchHere, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 280, 190));

        jLabelBg.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabelBg.setForeground(new java.awt.Color(204, 0, 0));
        jLabelBg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jarvis/images/bginputstream.png"))); // NOI18N
        jLabelBg.setIconTextGap(0);
        getContentPane().add(jLabelBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1035, 516));

        setSize(new java.awt.Dimension(1035, 516));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelTouchHereMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTouchHereMouseEntered
        MainPanel.mousesounds[0].playsound();
    }//GEN-LAST:event_jLabelTouchHereMouseEntered

    private void jLabelTouchHereMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTouchHereMouseClicked
       MainPanel.mousesounds[1].playsound();
       setTextEnteredField();
       this.setVisible(false);
    }//GEN-LAST:event_jLabelTouchHereMouseClicked

    private void jLabelTouchHereKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabelTouchHereKeyReleased
        if (evt.getKeyCode()== KeyEvent.VK_ENTER){
            MainPanel.mousesounds[1].playsound();
            setTextEnteredField();
            this.setVisible(false);
        }
    }//GEN-LAST:event_jLabelTouchHereKeyReleased

    private void jTextFieldInputKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldInputKeyReleased
        if (evt.getKeyCode()== KeyEvent.VK_ENTER){
            MainPanel.mousesounds[1].playsound();
            setTextEnteredField();
            this.setVisible(false);
        }
    }//GEN-LAST:event_jTextFieldInputKeyReleased

    /**
     */
    public void showFrame() {
        setAlwaysOnTop(true);
        setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelBg;
    private javax.swing.JLabel jLabelTouchHere;
    public javax.swing.JTextField jTextFieldInput;
    // End of variables declaration//GEN-END:variables

    private void reInitialize() {
         URL resource = BlackBoard.class.getResource("/jarvis/images/bigme.gif");
         setIconImage(new ImageIcon(resource).getImage());
         showFrame();
    }

    private void setTextEnteredField() {
        textEntered = jTextFieldInput.getText();
    }
}
